.TH sleepuntil 1 "May 2024" "1.0" "sleepuntil man page"
.SH NAME
sleepuntil \- sleep until a specified datetime
.SH SYNOPSIS
.B sleepuntil
[\-v] <datetime>
.SH DESCRIPTION
The
.B sleepuntil
command sleeps until the specified datetime is reached.
.SH OPTIONS
.TP
.BR \-v
Enable verbose mode.
.TP
.BR \-h
Help message.
.SH EXAMPLES
.TP
.BR sleepuntil " 'tomorrow 8:00'"
Sleep until tomorrow 8:00.
.TP
.BR sleepuntil " 10pm " && " evening_task"
Sleeps until 10pm, then evening_task is executed.
.SH AUTHOR
Mattia Mascarello <mattia.mascarello@edu.unito.it>
.SH BUGS
Report bugs to: https://github.com/MatMasIt/sleepuntil
.SH COPYRIGHT
Copyright \(co 2024 Mattia Mascarello